export function errorLoggingDecorator(logger) {
    const handleError = (error) => logger.error(error);
    return function validator(target, _context) {
        return function (...args) {
            try {
                const result = target.apply(this, args);
                if (result instanceof Promise) {
                    result.catch(handleError);
                }
                return result;
            }
            catch (error) {
                handleError(error);
                throw error;
            }
        };
    };
}
//# sourceMappingURL=errorLoggingDecorator.js.map